package io.github.fmweigl.theappthatgivesyourecipes.buildlogic

import org.gradle.api.DefaultTask
import org.gradle.api.GradleException
import org.gradle.api.Project
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.Property
import org.gradle.api.provider.Provider
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction
import org.gradle.kotlin.dsl.register
import org.gradle.work.DisableCachingByDefault
import org.jetbrains.kotlin.gradle.dsl.KotlinMultiplatformExtension

private const val PROPERTY_NAME = "appVersionCode"
private const val DEFAULT_VERSION_CODE = 1

/** MSI and EXE installers allow at most this in the third part of the version (`1.0.<code>`). */
const val MAX_DESKTOP_VERSION_CODE = 65535

/**
 * The app's version, the same on every platform: the [code] is the Gradle property `appVersionCode`
 * (CI passes the GitHub run number; default 1) and the [name] is `1.0.<code>`.
 */
data class AppVersion(val code: Int) {

    val name: String get() = "1.0.$code"

    /** Fails when the desktop installers (MSI/EXE) can't carry this version. */
    fun requireDesktopPackagable() {
        if (code > MAX_DESKTOP_VERSION_CODE) {
            throw GradleException(
                "'$PROPERTY_NAME' is $code, but MSI/EXE installers allow at most $MAX_DESKTOP_VERSION_CODE " +
                    "in the version's third number ($name). Package the desktop app with a lower '$PROPERTY_NAME'.",
            )
        }
    }

    /**
     * The version for MSI installers: the [name], or, when the [code] is too high, a valid placeholder.
     * The Compose plugin rejects an invalid MSI version while configuring the project, which would break
     * every build (CI's Android build configures the desktop app too); `checkDesktopVersion` still stops
     * the installer tasks with a clear message.
     */
    val msiPackageVersion: String
        get() = if (code <= MAX_DESKTOP_VERSION_CODE) name else AppVersion(MAX_DESKTOP_VERSION_CODE).name

    /** The contents of iOS's `Version.xcconfig`, which `Config.xcconfig` includes. */
    fun toXcconfig(): String = """
        |// Generated by the writeIosVersionConfig task. Do not edit, and do not commit.
        |MARKETING_VERSION = $name
        |CURRENT_PROJECT_VERSION = $code
        |
    """.trimMargin()

    companion object {
        /** The version for the property's [value]; missing or blank means the default code 1. */
        fun fromProperty(value: String?): AppVersion {
            val text = value?.trim().orEmpty()
            if (text.isEmpty()) return AppVersion(DEFAULT_VERSION_CODE)
            val code = text.toIntOrNull()
            if (code == null || code < 1) {
                throw GradleException("'$PROPERTY_NAME' must be a positive whole number, not '$text'.")
            }
            return AppVersion(code)
        }
    }
}

/** The app's [AppVersion] from the Gradle property `appVersionCode`. */
fun Project.appVersion(): Provider<AppVersion> =
    providers.gradleProperty(PROPERTY_NAME).map { AppVersion.fromProperty(it) }.orElse(AppVersion(DEFAULT_VERSION_CODE))

/** Fails the desktop packaging tasks when the version can't go into an MSI/EXE installer. */
@DisableCachingByDefault(because = "A check without outputs")
abstract class CheckDesktopVersion : DefaultTask() {

    @get:Input
    abstract val versionCode: Property<Int>

    @TaskAction
    fun check() {
        AppVersion(versionCode.get()).requireDesktopPackagable()
    }
}

/**
 * Registers `checkDesktopVersion` and makes the MSI and EXE installer tasks (`package*Msi`,
 * `package*Exe`) depend on it; Deb and DMG have no such limit. Call it from the desktop app's build file.
 */
fun Project.requireDesktopPackagableVersion() {
    val check = tasks.register<CheckDesktopVersion>("checkDesktopVersion") {
        description = "Fails if the app version is too high for MSI/EXE installers ($MAX_DESKTOP_VERSION_CODE)."
        versionCode.set(appVersion().map { it.code })
    }
    tasks.matching { it.name.startsWith("package") && ("Msi" in it.name || "Exe" in it.name) }
        .configureEach { dependsOn(check) }
}

/** Writes `AppVersion.kt` with `internal const val APP_VERSION_NAME` and `APP_VERSION_CODE`. */
@DisableCachingByDefault(because = "The version changes with every CI run")
abstract class GenerateAppVersion : DefaultTask() {

    @get:Input
    abstract val versionName: Property<String>

    @get:Input
    abstract val versionCode: Property<Int>

    @get:Input
    abstract val packageName: Property<String>

    @get:OutputDirectory
    abstract val outputDirectory: DirectoryProperty

    @TaskAction
    fun generate() {
        val directory = outputDirectory.get().asFile
        directory.deleteRecursively()
        val packageDirectory = directory.resolve(packageName.get().replace('.', '/')).apply { mkdirs() }
        packageDirectory.resolve("AppVersion.kt").writeText(
            """
            |// Generated by the generateAppVersion task. Do not edit, and do not commit.
            |package ${packageName.get()}
            |
            |internal const val APP_VERSION_NAME: String = "${versionName.get()}"
            |internal const val APP_VERSION_CODE: Int = ${versionCode.get()}
            |
            """.trimMargin(),
        )
    }
}

/** Writes iOS's `Version.xcconfig` (`MARKETING_VERSION`, `CURRENT_PROJECT_VERSION`). */
@DisableCachingByDefault(because = "The version changes with every CI run")
abstract class WriteIosVersionConfig : DefaultTask() {

    @get:Input
    abstract val versionCode: Property<Int>

    @get:OutputFile
    abstract val outputFile: RegularFileProperty

    @TaskAction
    fun write() {
        outputFile.get().asFile.writeText(AppVersion(versionCode.get()).toXcconfig())
    }
}

/**
 * Generates commonMain's `APP_VERSION_NAME` and `APP_VERSION_CODE` constants in [packageName] from
 * [appVersion], and registers `writeIosVersionConfig`, which writes `iosApp/Configuration/Version.xcconfig`
 * (gitignored; `Config.xcconfig` includes it if present).
 */
fun KotlinMultiplatformExtension.appVersionSource(project: Project, packageName: String) {
    val version = project.appVersion()
    val generate = project.tasks.register<GenerateAppVersion>("generateAppVersion") {
        description = "Generates the app version constants from '$PROPERTY_NAME'."
        versionName.set(version.map { it.name })
        versionCode.set(version.map { it.code })
        this.packageName.set(packageName)
        outputDirectory.set(project.layout.buildDirectory.dir("generated/appVersion/commonMain/kotlin"))
    }
    sourceSets.commonMain.configure { kotlin.srcDir(generate.flatMap { it.outputDirectory }) }
    // So the IDE resolves the constants right after a Gradle sync.
    project.tasks.matching { it.name == "prepareKotlinIdeaImport" }.configureEach { dependsOn(generate) }

    project.tasks.register<WriteIosVersionConfig>("writeIosVersionConfig") {
        description = "Writes iosApp/Configuration/Version.xcconfig from '$PROPERTY_NAME'."
        versionCode.set(version.map { it.code })
        outputFile.set(project.rootProject.layout.projectDirectory.file("iosApp/Configuration/Version.xcconfig"))
    }
}
