package io.github.fmweigl.theappthatgivesyourecipes.core.designsystem

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// A kitchen palette: paprika (primary), basil (secondary) and saffron (tertiary) on warm cream
// surfaces in light mode and espresso surfaces in dark mode. The tones follow Material 3's
// tonal roles, so every on-color keeps a contrast of at least 4.5:1 (see ColorContrastTest).

internal val LightColorScheme = lightColorScheme(
    primary = Color(0xFFA8401E),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFDBCF),
    onPrimaryContainer = Color(0xFF3A0A00),
    inversePrimary = Color(0xFFFFB59C),
    secondary = Color(0xFF4C6B30),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFCDEEAA),
    onSecondaryContainer = Color(0xFF112000),
    tertiary = Color(0xFF7A5900),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFDEA0),
    onTertiaryContainer = Color(0xFF261900),
    background = Color(0xFFFFF8F0),
    onBackground = Color(0xFF1F1B16),
    surface = Color(0xFFFFF8F0),
    onSurface = Color(0xFF1F1B16),
    surfaceVariant = Color(0xFFF2DFD1),
    onSurfaceVariant = Color(0xFF51443B),
    surfaceTint = Color(0xFFA8401E),
    inverseSurface = Color(0xFF352F2A),
    inverseOnSurface = Color(0xFFF9EFE7),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    outline = Color(0xFF84746A),
    outlineVariant = Color(0xFFD6C3B6),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFFFFF8F0),
    surfaceContainer = Color(0xFFF6ECE2),
    surfaceContainerHigh = Color(0xFFF1E6DC),
    surfaceContainerHighest = Color(0xFFEBE0D6),
    surfaceContainerLow = Color(0xFFFCF2E8),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceDim = Color(0xFFE2D8CE),
)

internal val DarkColorScheme = darkColorScheme(
    primary = Color(0xFFFFB59C),
    onPrimary = Color(0xFF5C1900),
    primaryContainer = Color(0xFF852B0C),
    onPrimaryContainer = Color(0xFFFFDBCF),
    inversePrimary = Color(0xFFA8401E),
    secondary = Color(0xFFB1D18F),
    onSecondary = Color(0xFF1F3706),
    secondaryContainer = Color(0xFF354E1B),
    onSecondaryContainer = Color(0xFFCDEEAA),
    tertiary = Color(0xFFF2BF48),
    onTertiary = Color(0xFF402D00),
    tertiaryContainer = Color(0xFF5C4200),
    onTertiaryContainer = Color(0xFFFFDEA0),
    background = Color(0xFF18120E),
    onBackground = Color(0xFFEDE0D8),
    surface = Color(0xFF18120E),
    onSurface = Color(0xFFEDE0D8),
    surfaceVariant = Color(0xFF51443B),
    onSurfaceVariant = Color(0xFFD6C3B6),
    surfaceTint = Color(0xFFFFB59C),
    inverseSurface = Color(0xFFEDE0D8),
    inverseOnSurface = Color(0xFF362F2A),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    outline = Color(0xFF9F8D82),
    outlineVariant = Color(0xFF51443B),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFF3F3833),
    surfaceContainer = Color(0xFF251E1A),
    surfaceContainerHigh = Color(0xFF2F2924),
    surfaceContainerHighest = Color(0xFF3A332E),
    surfaceContainerLow = Color(0xFF201A16),
    surfaceContainerLowest = Color(0xFF120D0A),
    surfaceDim = Color(0xFF18120E),
)
