package io.github.fmweigl.yetanothermealsapp.buildlogic

import org.gradle.api.DefaultTask
import org.gradle.api.GradleException
import org.gradle.api.Project
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import org.gradle.kotlin.dsl.register
import org.gradle.work.DisableCachingByDefault
import org.jetbrains.kotlin.gradle.dsl.KotlinMultiplatformExtension
import java.util.Properties

private const val PROPERTY_NAME = "theMealDbApiKey"
private const val ENVIRONMENT_VARIABLE = "THE_MEAL_DB_API_KEY"

/** TheMealDB's public key for development, used when no supporter key is configured. */
private const val TEST_API_KEY = "1"

/** Writes `TheMealDbApiKey.kt`, which holds the API key as `internal const val THE_MEAL_DB_API_KEY`. */
// Kept out of the build cache, so the key only ends up in this project's build directory.
@DisableCachingByDefault(because = "Holds a secret")
abstract class GenerateTheMealDbApiKey : DefaultTask() {

    @get:Input
    abstract val apiKey: Property<String>

    @get:Input
    abstract val packageName: Property<String>

    @get:OutputDirectory
    abstract val outputDirectory: DirectoryProperty

    @TaskAction
    fun generate() {
        val key = apiKey.get()
        // Also keeps the key from breaking the generated string literal or the request URL.
        if (!key.matches(Regex("[A-Za-z0-9_-]+"))) {
            throw GradleException("The TheMealDB API key ('$PROPERTY_NAME') may only contain letters, digits, '_' and '-'.")
        }
        val directory = outputDirectory.get().asFile
        directory.deleteRecursively()
        val packageDirectory = directory.resolve(packageName.get().replace('.', '/')).apply { mkdirs() }
        packageDirectory.resolve("TheMealDbApiKey.kt").writeText(
            """
            |// Generated by the generateTheMealDbApiKey task. Do not edit, and do not commit.
            |package ${packageName.get()}
            |
            |internal const val THE_MEAL_DB_API_KEY: String = "$key"
            |
            """.trimMargin(),
        )
    }
}

/**
 * Generates commonMain's `THE_MEAL_DB_API_KEY` constant in [packageName]. The key is taken from the
 * first of: the Gradle property `theMealDbApiKey` (e.g. in `~/.gradle/gradle.properties`), the same
 * key in the root `local.properties` (not committed), the `THE_MEAL_DB_API_KEY` environment
 * variable (CI); without any, TheMealDB's public test key `1`.
 */
fun KotlinMultiplatformExtension.theMealDbApiKeySource(project: Project, packageName: String) {
    val providers = project.providers
    val localProperties = project.rootProject.layout.projectDirectory.file("local.properties")
    val fromLocalProperties = providers.fileContents(localProperties).asText.map { text ->
        Properties().apply { load(text.reader()) }.getProperty(PROPERTY_NAME).orEmpty()
    }.filter { it.isNotBlank() }

    val generate = project.tasks.register<GenerateTheMealDbApiKey>("generateTheMealDbApiKey") {
        description = "Generates the TheMealDB API key constant from '$PROPERTY_NAME' or $ENVIRONMENT_VARIABLE."
        apiKey.set(
            providers.gradleProperty(PROPERTY_NAME)
                .orElse(fromLocalProperties)
                .orElse(providers.environmentVariable(ENVIRONMENT_VARIABLE))
                .map(String::trim)
                .orElse(TEST_API_KEY),
        )
        this.packageName.set(packageName)
        outputDirectory.set(project.layout.buildDirectory.dir("generated/theMealDbApiKey/commonMain/kotlin"))
    }
    sourceSets.commonMain.configure { kotlin.srcDir(generate.flatMap { it.outputDirectory }) }
    // So the IDE resolves the constant right after a Gradle sync.
    project.tasks.matching { it.name == "prepareKotlinIdeaImport" }.configureEach { dependsOn(generate) }
}
